<?php
session_start();

$ID = $_POST['ValidID'];

try {
    $connection = new PDO('mysql:host=127.0.0.1;dbname=NEU_IS', 'root', '');
    } catch (PDOException $e) {
        die('Could not connect.');
    }

    $statement = $connection->prepare("INSERT INTO NEU_IS.STUDENTINFO(FROMYEAR, TOYEAR, LRN, GRADELEVEL, LASTNAME, FIRSTNAME, MIDDLENAME, BIRTHDATE, BIRTHMUNTOWCITY, BIRTHPROVINCE, GENDER, LASTSCHOOLATTENDED, LASTSCHOOLYEAR, LASTSCHOOLGRADELEVEL,LASTSCHOOLADDRESS) SELECT FROMYEAR, TOYEAR, LRN, GRADELEVEL, LASTNAME, FIRSTNAME, MIDDLENAME, BIRTHDATE, BIRTHMUNTOWCITY, BIRTHPROVINCE, GENDER, LASTSCHOOLATTENDED, LASTSCHOOLYEAR, LASTSCHOOLGRADELEVEL,LASTSCHOOLADDRESS FROM NEU_IS_APPLICATION.STUDENTINFOTEMP WHERE ID = $ID");
    $statement1 = $connection->prepare("INSERT INTO NEU_IS.CITIZEN(CITIZENSHIP, VISATYPE, VISAISSUEDIN, VEXPIRATION, PASSPORTNO, PISSUEDIN, PEXPIRATION, COMPLETEADDRESS, CONTACTNO) SELECT CITIZENSHIP, VISATYPE, VISAISSUEDIN, VEXPIRATION, PASSPORTNO, PISSUEDIN, PEXPIRATION, COMPLETEADDRESS, CONTACTNO FROM NEU_IS_APPLICATION.CITIZENTEMP WHERE ID = $ID");
    $statement2 = $connection->prepare("INSERT INTO NEU_IS.RELIGION(RELIGIOUSAFFILIATION, INCAREA, INCGROUP, INCLOCALE, INCDISTRICT, INCRECOMMENDNAME, INCRECOMMENDADDRESS, INCRECOMMENDCONTACTNO) SELECT RELIGIOUSAFFILIATION, INCAREA, INCGROUP, INCLOCALE, INCDISTRICT, INCRECOMMENDNAME, INCRECOMMENDADDRESS, INCRECOMMENDCONTACTNO FROM NEU_IS_APPLICATION.RELIGIONTEMP WHERE ID = $ID");
    $statement3 = $connection->prepare("INSERT INTO NEU_IS.PARENTS(FATHERNAME,FATHERRELIGION,FATHERLOCALE,FATHERADDRESS,FATHERCONTACT,FATHEROCCUPATION,FATHERWORKADDRESS,FATHERWORKCONTACTNO,MOTHERNAME,MOTHERRELIGION,MOTHERLOCALE,MOTHERADDRESS,MOTHERCONTACT,MOTHEROCCUPATION,MOTHERWORKADDRESS,MOTHERWORKCONTACTNO) SELECT FATHERNAME,FATHERRELIGION,FATHERLOCALE,FATHERADDRESS,FATHERCONTACT,FATHEROCCUPATION,FATHERWORKADDRESS,FATHERWORKCONTACTNO,MOTHERNAME,MOTHERRELIGION,MOTHERLOCALE,MOTHERADDRESS,MOTHERCONTACT,MOTHEROCCUPATION,MOTHERWORKADDRESS,MOTHERWORKCONTACTNO FROM NEU_IS_APPLICATION.PARENTSTEMP WHERE ID = $ID");


    $statement->execute();
    $_SESSION['ValID'] = $connection->lastInsertId();
    $statement1->execute();
    $statement2->execute();
    $statement3->execute();

    header('Location: ConfirmValidation.php');

?>